FROM node:20-alpine
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package*.json ./
RUN npm install --ignore-scripts --legacy-peer-deps
RUN npm install 
COPY . .
EXPOSE 5173
CMD ["npm", "run", "dev"]