import avatar from "./avatar.png";

export type Freelancer = {
  id: string;
  avatar: string;
  price: number;
  name: string;
  title: string;
  categorie?: string;
  expLevel: "Junior" | "Mid" | "Sunior";
  skills: string[];
};

export const freelencer: Freelancer[] = [
  {
    id: "0",
    avatar,
    price: 80,
    name: "Sarah Jenkins",
    title: "Senior Frontend Architect",
    categorie: "Web Development",
    expLevel: "Junior",
    skills: ["React", "Vue.js", "Figma", "React", "Vue.js", "Figma"],
  },
  {
    id: "1",
    avatar,
    price: 60,
    name: "Sarah Jenkins",
    title: "Senior Frontend Architect",
    categorie: "Web Development",
    expLevel: "Junior",
    skills: ["React", "Vue.js", "Figma"],
  },
  {
    id: "2",
    avatar,
    price: 60,
    name: "Sarah Jenkins",
    title: "Senior Frontend Architect",
    categorie: "Web Development",
    expLevel: "Junior",
    skills: ["React", "Vue.js", "Figma"],
  },
  {
    id: "3",
    avatar,
    price: 60,
    name: "Sarah Jenkins",
    title: "Senior Frontend Architect",
    categorie: "Web Development",
    expLevel: "Junior",
    skills: ["React", "Vue.js", "Figma"],
  },
  {
    id: "4",
    avatar,
    price: 50,
    name: "Sarah Jenkins",
    title: "Senior Frontend Architect",
    categorie: "Web Development",
    expLevel: "Junior",
    skills: ["React", "Vue.js", "Figma"],
  },
  {
    id: "5",
    avatar,
    price: 50,
    name: "Sarah Jenkins",
    title: "Senior Frontend Architect",
    categorie: "Web Development",
    expLevel: "Junior",
    skills: ["React", "Vue.js", "Figma"],
  },
  {
    id: "6",
    avatar,
    price: 50,
    name: "Sarah Jenkins",
    title: "Senior Frontend Architect",
    expLevel: "Junior",
    skills: ["React", "Vue.js", "Figma"],
  },
  {
    id: "7",
    avatar,
    price: 40,
    name: "Sarah Jenkins",
    title: "Senior Frontend Architect",
    categorie: "Web Development",
    expLevel: "Junior",
    skills: ["React", "Vue.js", "Figma"],
  },
  {
    id: "8",
    avatar,
    price: 40,
    name: "Sarah Jenkins",
    title: "Senior Frontend Architect",
    categorie: "Web Development",
    expLevel: "Mid",
    skills: ["React", "Vue.js", "Figma"],
  },
  {
    id: "9",
    avatar,
    price: 30,
    name: "Sarah Jenkins",
    title: "Senior Frontend Architect",
    categorie: "Mobile Apps",
    expLevel: "Mid",
    skills: ["React", "Vue.js", "Figma"],
  },
  {
    id: "10",
    avatar,
    price: 30,
    name: "Sarah Jenkins",
    title: "Senior Frontend Architect",
    categorie: "Mobile Apps",
    expLevel: "Mid",
    skills: ["Vue.js", "Figma"],
  },
  {
    id: "11",
    avatar,
    price: 20,
    name: "Sarah Jenkins",
    title: "Senior Frontend Architect",
    categorie: "Mobile Apps",
    expLevel: "Mid",
    skills: ["Vue.js", "Figma"],
  },
  {
    id: "12",
    avatar,
    price: 20,
    name: "Sarah Jenkins",
    title: "Senior Frontend Architect",
    categorie: "Mobile Apps",
    expLevel: "Mid",
    skills: ["React", "Vue.js", "Figma"],
  },
  {
    id: "13",
    avatar,
    price: 20,
    name: "Sarah Jenkins",
    title: "Senior Frontend Architect",
    categorie: "Graphic Design",
    expLevel: "Mid",
    skills: ["React", "Vue.js", "Figma"],
  },
  {
    id: "14",
    avatar,
    price: 10,
    name: "Sarah Jenkins",
    title: "Senior Frontend Architect",
    categorie: "Graphic Design",
    expLevel: "Mid",
    skills: ["React", "Vue.js", "Figma"],
  },
  {
    id: "15",
    avatar,
    price: 10,
    name: "Sarah Jenkins",
    title: "Senior Frontend Architect",
    categorie: "Graphic Design",
    expLevel: "Sunior",
    skills: ["React", "Vue.js", "Figma"],
  },
  {
    id: "16",
    avatar,
    price: 10,
    name: "Sarah Jenkins",
    title: "Senior Frontend Architect",
    categorie: "Graphic Design",
    expLevel: "Sunior",
    skills: ["Vue.js", "Figma"],
  },
  {
    id: "17",
    avatar,
    price: 50,
    name: "Sarah Jenkins",
    title: "Senior Frontend Architect",
    categorie: "Graphic Design",
    expLevel: "Sunior",
    skills: ["Vue.js", "Figma"],
  },
  {
    id: "18",
    avatar,
    price: 30,
    name: "Sarah Jenkins",
    title: "Senior Frontend Architect",
    categorie: "Graphic Design",
    expLevel: "Sunior",
    skills: ["React", "Vue.js", "Figma", "React"],
  },
  {
    id: "19",
    avatar,
    price: 70,
    name: "Sarah Jenkins",
    title: "Senior Frontend Architect",
    categorie: "Graphic Design",
    expLevel: "Sunior",
    skills: ["Vue.js", "Figma"],
  },
];


export type CategoriesData = {
  [key: string]: string[];
};

export const categoriesData: CategoriesData = {
  "Web Development": [
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "Next.js",
    "Vue.js",
    "Angular",
    "Node.js",
    "Express",
    "TypeScript",
    "Tailwind CSS",
    "Bootstrap",
    "PHP",
    "Laravel",
    "Django",
    "Ruby on Rails",
    "REST API",
    "GraphQL",
  ],

  "UI/UX Design": [
    "Figma",
    "Adobe XD",
    "Sketch",
    "Wireframing",
    "Prototyping",
    "User Research",
    "Usability Testing",
    "Interaction Design",
    "Design Systems",
    "Mobile UI Design",
    "Web UI Design",
    "UX Writing",
    "Accessibility Design",
  ],

  "Mobile Apps": [
    "React Native",
    "Flutter",
    "Swift",
    "Kotlin",
    "Android Development",
    "iOS Development",
    "Ionic",
    "Xamarin",
    "Mobile UI Design",
    "App Performance Optimization",
  ],

  "Graphic Design": [
    "Photoshop",
    "Illustrator",
    "InDesign",
    "Brand Identity",
    "Logo Design",
    "Poster Design",
    "Typography",
    "Packaging Design",
    "Vector Art",
    "Motion Graphics",
    "3D Design",
  ],

  "Digital Marketing": [
    "SEO",
    "Google Ads",
    "Facebook Ads",
    "Content Marketing",
    "Email Marketing",
    "Affiliate Marketing",
    "Social Media Management",
    "Influencer Marketing",
    "Marketing Strategy",
    "Analytics",
    "Conversion Optimization",
  ],

  DevOps: [
    "AWS",
    "Docker",
    "Kubernetes",
    "CI/CD",
    "Jenkins",
    "GitHub Actions",
    "Terraform",
    "Linux",
    "Nginx",
    "Cloud Security",
  ],

  "Data Science": [
    "Python",
    "Machine Learning",
    "Deep Learning",
    "TensorFlow",
    "PyTorch",
    "Data Analysis",
    "Pandas",
    "NumPy",
    "Data Visualization",
    "Power BI",
    "Tableau",
  ],
};