import type { User, RoleDefinition, Job } from '../types';
import { ROLE_PERMISSIONS, ROLE_META } from './permissions';

export const MOCK_USERS: User[] = [
  { id: '1', name: 'Abdelali Mahfoudi',      email: 'admin@leetconnect.io',   role: 'admin',     status: 'active',    createdAt: '2024-01-10', avatar: 'AB' },
	{ id: '2', name: 'Cristiano Ronaldo',  email: 'ronaldo@leetconnect.io',  role: 'admin',      status: 'active',    createdAt: '2024-03-01', avatar: 'CR' },
  { id: '3', name: 'Lionel Messi',        email: 'messi@leetconnect.io',    role: 'moderator', status: 'active',    createdAt: '2024-02-14', avatar: 'LM' },
	{ id: '4', name: 'Kylian Mbappé',      email: 'mbappe@leetconnect.io',   role: 'user',      status: 'active', createdAt: '2024-03-15', avatar: 'KM' },
	{ id: '5', name: 'Kevin De Bruyne',    email: 'kdb@leetconnect.io',      role: 'moderator', status: 'active',    createdAt: '2024-04-02', avatar: 'KB' },
	{ id: '6', name: 'Victor Osimhen',     email: 'osimhen@leetconnect.io',  role: 'user',      status: 'pending',   createdAt: '2024-04-20', avatar: 'VO' },
	{ id: '7', name: 'Achraf Hakimi',      email: 'hakimi@leetconnect.io',   role: 'moderator',     status: 'active',    createdAt: '2024-05-05', avatar: 'AH' },
	{ id: '8', name: 'Erling Haaland',     email: 'haaland@leetconnect.io',  role: 'user',      status: 'active',    createdAt: '2024-05-18', avatar: 'EH' },
	{ id: '9',  name: 'Neymar Jr',           email: 'neymar@leetconnect.io',     role: 'user',      status: 'active',    createdAt: '2024-06-01', avatar: 'NJ' },
	{ id: '10', name: 'Mohamed Salah',       email: 'salah@leetconnect.io',      role: 'moderator', status: 'active',    createdAt: '2024-06-05', avatar: 'MS' },
	{ id: '11', name: 'Luka Modrić',         email: 'modric@leetconnect.io',     role: 'user',      status: 'active',    createdAt: '2024-06-10', avatar: 'LM' },
	{ id: '12', name: 'Karim Benzema',       email: 'benzema@leetconnect.io',    role: 'user',      status: 'pending',  createdAt: '2024-06-15', avatar: 'KB' },
	{ id: '13', name: 'Vinícius Jr',         email: 'vinicius@leetconnect.io',   role: 'guest',     status: 'suspended',    createdAt: '2024-06-20', avatar: 'VJ' },
	{ id: '14', name: 'Jude Bellingham',     email: 'bellingham@leetconnect.io', role: 'user',      status: 'active',   createdAt: '2024-06-25', avatar: 'JB' },
	{ id: '15', name: 'Pedri González',      email: 'pedri@leetconnect.io',      role: 'guest',      status: 'pending',    createdAt: '2024-07-01', avatar: 'PG' },
	{ id: '16', name: 'Robert Lewandowski',  email: 'lewa@leetconnect.io',       role: 'moderator', status: 'active',    createdAt: '2024-07-10', avatar: 'RL' },
	{ id: '17', name: 'Harry Kane',          email: 'kane@leetconnect.io',       role: 'user',      status: 'active',    createdAt: '2024-07-15', avatar: 'HK' },
	{ id: '18', name: 'Heung-min Son',       email: 'son@leetconnect.io',        role: 'guest',     status: 'active',    createdAt: '2024-07-20', avatar: 'HS' },
	{ id: '19', name: 'Bukayo Saka',         email: 'saka@leetconnect.io',       role: 'user',      status: 'active',    createdAt: '2024-07-25', avatar: 'BS' },
	{ id: '20', name: 'Phil Foden',          email: 'foden@leetconnect.io',      role: 'guest',      status: 'active',    createdAt: '2024-08-01', avatar: 'PF' },
	{ id: '21', name: 'Rodri Hernández',     email: 'rodri@leetconnect.io',      role: 'moderator', status: 'active',    createdAt: '2024-08-05', avatar: 'RH' },
	{ id: '22', name: 'Antoine Griezmann',   email: 'griezmann@leetconnect.io',  role: 'user',      status: 'pending',  createdAt: '2024-08-10', avatar: 'AG' },
	{ id: '23', name: 'Ousmane Dembélé',     email: 'dembele@leetconnect.io',    role: 'user',      status: 'active',    createdAt: '2024-08-15', avatar: 'OD' },
]

export const MOCK_JOBS: Job[] = [
  {
    id: 'j1',
    title: 'Senior React Developer for SaaS Dashboard',
    category: 'Frontend Dev',
    budget: 3500,
    budgetType: 'fixed',
    status: 'active',
    proposalCount: 12,
    postedBy: '3',
    postedByName: 'Lionel Messi',
    postedByAvatar: 'LM',
    createdAt: '2024-05-01',
    deadline: '2024-06-01',
    description: 'Looking for an experienced React developer to build a complex SaaS analytics dashboard with real-time data, charts, and role-based access control.',
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'Recharts'],
  },
  {
    id: 'j2',
    title: 'Node.js Backend API for E-commerce Platform',
    category: 'Backend Dev',
    budget: 85,
    budgetType: 'hourly',
    status: 'active',
    proposalCount: 7,
    postedBy: '6',
    postedByName: 'Kylian Mbappé',
    postedByAvatar: 'KM',
    createdAt: '2024-05-03',
    deadline: '2024-07-01',
    description: 'Need a Node.js expert to design and build RESTful APIs for a multi-vendor e-commerce platform. PostgreSQL, Redis caching, and Stripe integration required.',
    skills: ['Node.js', 'Express', 'PostgreSQL', 'Redis', 'Stripe'],
  },
  {
    id: 'j3',
    title: 'Mobile App UI/UX Redesign (iOS & Android)',
    category: 'UI/UX Design',
    budget: 2200,
    budgetType: 'fixed',
    status: 'flagged',
    proposalCount: 3,
    postedBy: '4',
    postedByName: 'Cristiano Ronaldo',
    postedByAvatar: 'CR',
    createdAt: '2024-05-05',
    deadline: '2024-05-30',
    description: 'Complete redesign of our mobile app. Need Figma prototypes, design system, and handoff files. Flagged for suspicious budget manipulation.',
    skills: ['Figma', 'iOS', 'Android', 'Prototyping', 'Design Systems'],
  },
  {
    id: 'j4',
    title: 'DevOps Engineer — CI/CD Pipeline Setup',
    category: 'DevOps',
    budget: 120,
    budgetType: 'hourly',
    status: 'active',
    proposalCount: 5,
    postedBy: '8',
    postedByName: 'Kevin De Bruyne',
    postedByAvatar: 'KD',
    createdAt: '2024-05-07',
    description: 'Set up GitHub Actions pipelines, Docker containerization, and Kubernetes deployment for our microservices architecture on AWS.',
    skills: ['Docker', 'Kubernetes', 'GitHub Actions', 'AWS', 'Terraform'],
  },
  {
    id: 'j5',
    title: 'Full Stack Next.js App with Supabase',
    category: 'Full Stack',
    budget: 5000,
    budgetType: 'fixed',
    status: 'active',
    proposalCount: 19,
    postedBy: '3',
    postedByName: 'Neymar Jr',
    postedByAvatar: 'NJ',
    createdAt: '2024-05-08',
    deadline: '2024-08-01',
    description: 'Build a full-stack web application using Next.js 14 App Router, Supabase for auth and database, and Stripe for payments.',
    skills: ['Next.js', 'Supabase', 'TypeScript', 'Stripe', 'Tailwind CSS'],
  },
  {
    id: 'j6',
    title: 'Python Data Pipeline & Dashboard',
    category: 'Data Science',
    budget: 4500,
    budgetType: 'fixed',
    status: 'closed',
    proposalCount: 8,
    postedBy: '7',
    postedByName: 'Mohamed Salah',
    postedByAvatar: 'MS',
    createdAt: '2024-04-15',
    deadline: '2024-05-15',
    description: 'Completed project — ETL pipeline with Airflow, data warehouse on BigQuery, and visualization dashboard using Metabase.',
    skills: ['Python', 'Airflow', 'BigQuery', 'Pandas', 'Metabase'],
  },
  {
    id: 'j7',
    title: 'React Native Fitness Tracking App',
    category: 'Mobile Dev',
    budget: 6000,
    budgetType: 'fixed',
    status: 'active',
    proposalCount: 0,
    postedBy: '8',
    postedByName: 'Erling Haaland',
    postedByAvatar: 'EH',
    createdAt: '2024-05-10',
    deadline: '2024-09-01',
    description: 'itness app with workout tracking, health integrations, and social features.',
    skills: ['React Native', 'Expo', 'HealthKit', 'Firebase'],
  },
  {
    id: 'j8',
    title: 'WordPress to Headless CMS Migration',
    category: 'Full Stack',
    budget: 2800,
    budgetType: 'fixed',
    status: 'active',
    proposalCount: 4,
    postedBy: '6',
    postedByName: 'Vinícius Jr',
    postedByAvatar: 'VJ',
    createdAt: '2024-05-11',
    description: 'Migrate existing WordPress site to Contentful + Next.js. Preserve all content, SEO, and add new blog features.',
    skills: ['Next.js', 'Contentful', 'WordPress', 'SEO', 'GraphQL'],
  },
  {
    id: 'j9',
    title: 'QA Automation Framework — Playwright',
    category: 'QA & Testing',
    budget: 60,
    budgetType: 'hourly',
    status: 'flagged',
    proposalCount: 2,
    postedBy: '4',
    postedByName: 'Luka Modrić',
    postedByAvatar: 'LM',
    createdAt: '2024-05-12',
    description: 'Flagged for duplicate posting. Set up Playwright test suite, write E2E tests for core user flows, integrate with CI pipeline.',
    skills: ['Playwright', 'TypeScript', 'CI/CD', 'Testing'],
  },
  {
    id: 'j10',
    title: 'Technical Blog Content Writer (SaaS)',
    category: 'Content Writing',
    budget: 150,
    budgetType: 'fixed',
    status: 'active',
    proposalCount: 31,
    postedBy: '3',
    postedByName: 'Jude Bellingham',
    postedByAvatar: 'JB',
    createdAt: '2024-05-14',
    description: 'Write 4 technical blog posts per month about SaaS, APIs, and developer tools. SEO-optimised, 1500-2000 words each.',
    skills: ['Technical Writing', 'SEO', 'Markdown', 'SaaS'],
  },
];

export const MOCK_ROLES: RoleDefinition[] = (['admin', 'moderator', 'user', 'guest'] as const).map(name => ({
  id: name,
  name,
  label: ROLE_META[name].label,
  description: ROLE_META[name].description,
  permissions: ROLE_PERMISSIONS[name],
  color: ROLE_META[name].color,
  userCount: MOCK_USERS.filter(u => u.role === name).length,
}));

// Simulated current logged-in user
export const MOCK_CURRENT_USER: User = MOCK_USERS[0]!; // admin